In [1]:
import torch

In [2]:
torch.empty(2,2,2)

tensor([[[ 0.0000e+00, -3.6893e+19],
         [ 2.6197e-28, -2.5244e-29]],

        [[ 1.1210e-44, -0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])

In [3]:
torch.zeros(2,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [10]:
x = torch.ones(2,2,2,dtype=int)
print(x)

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])


In [9]:
x.dtype

torch.int64

In [13]:
print(x.size())

torch.Size([2, 2, 2])


In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x * y
z = torch.mul(x,y)
print(z)
y.mul_(x)
print(y)

tensor([[0.0500, 0.3172],
        [0.0319, 0.2775]])
tensor([[0.0500, 0.3172],
        [0.0319, 0.2775]])


In [16]:
x= torch.rand(5,3)

In [18]:
print(x)
print(x[:,0])
print(x[0,:])

tensor([[0.8109, 0.4357, 0.3077],
        [0.5229, 0.7704, 0.7283],
        [0.9493, 0.1477, 0.7331],
        [0.1478, 0.7764, 0.9721],
        [0.0191, 0.4106, 0.8789]])
tensor([0.8109, 0.5229, 0.9493, 0.1478, 0.0191])
tensor([0.8109, 0.4357, 0.3077])


In [21]:
print(x[2,2])
print(x[2,2].item())

tensor(0.7331)
0.7331138849258423


In [22]:
x = torch.rand(4,4)
print(x)

print(x.view(16))

tensor([[0.6336, 0.7467, 0.8733, 0.8523],
        [0.8726, 0.8291, 0.3352, 0.0140],
        [0.6473, 0.3546, 0.7084, 0.0819],
        [0.4958, 0.0010, 0.3825, 0.4415]])
tensor([0.6336, 0.7467, 0.8733, 0.8523, 0.8726, 0.8291, 0.3352, 0.0140, 0.6473,
        0.3546, 0.7084, 0.0819, 0.4958, 0.0010, 0.3825, 0.4415])
